name: "Reusable Continuous Integration workflow"

on:

  workflow_call:

    secrets:
      GH_TOKEN:
        description: 'A Github PAT'
        required: false
      CODECOV_TOKEN:
        description: 'Needed to upload coverage report to codecov'
        required: false

    inputs:

      draft-release:
        # This should be a Boolean, but https://github.com/actions/runner/issues/1483
        description: "Set to true, if the workflow shall draft a release"
        required: false
        default: "false"
        type: string

      # documentation-artifact:
      #   description: "Name of the html documentation artifact. Will be build on Windows. Leave empty to skip documentation build."
      #   required: false
      #   default: ''
      #   type: string

      api-tests:
        # This should be a Boolean, but https://github.com/actions/runner/issues/1483
        description: "Run api tests"
        required: false
        default: "false"
        type: string

      win-package-artifact:
        description: "Name of the windows package artifact. Leave empty to skip building the package."
        required: false
        default: ''
        type: string

      win-installer-artifact:
        description: "Name of the windows installer artifact. Leave empty to skip building the installer."
        required: false
        default: ''
        type: string

      # macos-package-artifact:
      #   description: "Name of the Mac OS package artifact. Leave empty to skip building the package."
      #   required: false
      #   default: ''
      #   type: string

jobs:

  build-linux:
    strategy:
      matrix:
        config: ["Debug", "Release"]
        os: ["ubuntu-latest", "ubuntu-22.04"]
        # only enable coverage for Debug build on latest ubuntu
        include:
          - config: "Debug"
            os: "ubuntu-22.04"
            coverage: "ON"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/build-linux
        with:
          config: ${{ matrix.config }}
          geoml_enable_coverage: ${{ matrix.coverage || 'OFF' }}
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-cov-${{ matrix.coverage || 'OFF' }}


  test-linux:
    needs: build-linux
    strategy:
      matrix:
        config: ["Debug", "Release"]
        os: ["ubuntu-latest", "ubuntu-22.04"]
        unit-tests: [true]
        api-tests: [true]
        # generate coverage reports on latest ubuntu debug builds
        exclude:
          - config: "Debug"
            os: "ubuntu-22.04"
        include:
          - config: "Debug"
            os: "ubuntu-22.04"
            coverage: "ON"
            unit-tests: false
            api-tests: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/test-linux
        with:
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-cov-${{ matrix.coverage || 'OFF' }}
          coverage: ${{ matrix.coverage == 'ON' || false }}
          unit-tests: ${{ matrix.unit-tests }}
          api-tests: ${{ matrix.api-tests }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}


  build-windows:
    strategy:
      matrix:
        config: ["Release"]
        os: ["windows-latest"]
        include:
         - config: "Release"
           os: "windows-latest"
           oce_static_libs: "ON"
           #geoml_bindings_python_internal: "ON"
           #documentation-artifact: ${{ inputs.documentation-artifact }}
           package-artifact: ${{ inputs.win-package-artifact }}
           installer-artifact: ${{ inputs.win-installer-artifact }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/build-win
        with:
          config: ${{ matrix.config }}
          geoml_enable_coverage: 'OFF'
          oce_static_libs: ${{ matrix.oce_static_libs || 'OFF' }}
          #geoml_bindings_python_internal: ${{ matrix.geoml_bindings_python_internal || 'OFF' }}
          #documentation-artifact: ${{ matrix.documentation-artifact }}
          package-artifact: ${{ matrix.package-artifact }}
          installer-artifact: ${{ matrix.installer-artifact }}
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-cov-OFF-static-${{ matrix.oce_static_libs || 'OFF' }}#-python-${{ matrix.geoml_bindings_python_internal || 'OFF' }}

  test-windows:
    needs: build-windows
    strategy:
      matrix:
        config: ["Release"]
        os: ["windows-latest"]
        include:
         - config: "Release"
           os: "windows-latest"
           oce_static_libs: "ON"
           #geoml_bindings_python_internal: "ON"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/test-win
        with:
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-cov-OFF-static-${{ matrix.oce_static_libs || 'OFF' }}#-python-${{ matrix.geoml_bindings_python_internal || 'OFF' }}
          unit-tests: true
          api-tests: ${{ inputs.api-tests == 'true' }}

  build-macos:
    runs-on: "macos-13"
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/build-macos
        with:
          config: "Release"
          geoml_enable_coverage: 'OFF'
          package-artifact: ${{ inputs.macos-package-artifact }}
          build-artifact: build-macos-13-Release-cov-OFF-static-ON-python-OFF

  test-macos:
    needs: build-macos
    runs-on: "macos-13"
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/test-macos
        with:
          build-artifact: build-macos-13-Release-cov-OFF-static-ON-python-OFF
          unit-tests: true
          api-tests: ${{ inputs.api-tests == 'true' }}

