name: CI workflow for main branch

on:
  schedule:
    - cron: "40 2 * * *"
  push:
    branches:
      - 'main'
      - 'github-actions-2'
    tags:
      - v*
  workflow_dispatch:

jobs:

  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    secrets: inherit
    with:
      draft-release: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
      #documentation-artifact: 'html-documentation'
      api-tests: true
      win-installer-artifact: 'win-installer'
      win-package-artifact: 'win-package'
      # macos-package-artifact: 'macos-package'
